alexnet:
    onnx_file:     "../alexnet.onnx"
    engine_file:   "../alexnet.trt"
    labels_file:   "../label.txt"
    BATCH_SIZE:    1
    INPUT_CHANNEL: 3
    IMAGE_WIDTH:   224
    IMAGE_HEIGHT:  224
    img_mean:      [0.485, 0.456, 0.406]
    img_std:       [0.229, 0.224, 0.225]
